#disable_all_formatting = true
max_width = 76
reorder_imports = true
#blank_lines_lower_bound = 1
comment_width = 72
edition = "2021"
fn_params_layout = "Vertical"
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"

ignore = [
    "file1.rs",
    "file2.rs",
]

imports_layout = "Vertical"
force_multiline_blocks = true
indent_style = "Visual"
match_arm_blocks = true
match_block_trailing_comma = true
merge_derives = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
spaces_around_ranges = true
